language: java
notifications:
  slack:
    rooms:
      - hexanom:lPch9X1hMxDdtUiNxEUExZQX#development
install:
  - ./gradlew assemble
script:
  - ./gradlew check
after_success:
  - ./gradlew cobertura coveralls
