language: java
notifications:
  slack:
    rooms:
      - hexanom:lPch9X1hMxDdtUiNxEUExZQX#development
install:
  - gradle assemble
script:
  - gradle check
after_success:
  - gradle cobertura coveralls
